jwt:
  secret:
    5HaKUQmd9zp/GzfY/2Fr2U5reyVRNSJ0rhF5J2TGwWk=
spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
  profiles:
    include: db
