
spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
  profiles:
    include: db

jwt:
  secret: bXlTdXBlclNlY3JldEtleVRoYXROZWVkc1RvQmVBdExlYXN0MzJCeXRlc0xvbmdPck1vcmVGb3JIUzI1NjY=